<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZsz1Ic\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZsz1Ic/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZsz1Ic.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZsz1Ic\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCZsz1Ic\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CZsz1Ic',
    'container.build_id' => 'f0901f09',
    'container.build_time' => 1587239832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZsz1Ic');
